/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package wastecollectiondbms;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

public class EditProfile extends javax.swing.JInternalFrame {
    
    String strCustomerID;
    
    public void infoMessage(String strMessage, String strTitle){
        JOptionPane.showMessageDialog(null, strMessage, strTitle, JOptionPane.INFORMATION_MESSAGE);
    }
    
    public EditProfile(String customerID) {
        initComponents();
        this.strCustomerID = customerID;
            try{
            String strDriver = "com.mysql.jdbc.Driver";
            String strConn = "jdbc:mysql://localhost:3306/swcdbms";
            String strUser = "root";
            String strPass = "";
            Class.forName(strDriver);
            Connection objConn = DriverManager.getConnection(strConn,strUser,strPass);
            System.out.println(strCustomerID);
            
            String strQuery = "SELECT * FROM CUSTOMER WHERE customer_id ="+strCustomerID+"";
            Statement stmntQuery = objConn.prepareStatement(strQuery);
            ResultSet resSet = stmntQuery.executeQuery(strQuery);
            resSet.next();
            
            String customerFN = resSet.getString(2);
            String customerLN = resSet.getString(3);
            String customerPH = resSet.getString(4);
            String customerMail = resSet.getString(5);
            
            customerFirstNameTF.setText(customerFN);
            customerLastNameTF.setText(customerLN);
            customerPhoneTF.setText(customerPH);
            customerEmailTF.setText(customerMail);  
        }catch(Exception objError){
            System.out.println(objError);
        }  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        customerFirstNameTF = new javax.swing.JTextField();
        customerLastNameTF = new javax.swing.JTextField();
        customerPhoneTF = new javax.swing.JTextField();
        customerEmailTF = new javax.swing.JTextField();
        editBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        editPassBtn = new javax.swing.JButton();
        updatePassBtn = new javax.swing.JButton();
        oldPassPF = new javax.swing.JPasswordField();
        newPassPF = new javax.swing.JPasswordField();
        confirmNewPassPF = new javax.swing.JPasswordField();

        setClosable(true);
        setIconifiable(true);
        setTitle("User Profile Settings");

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        jLabel1.setText("PROFILE SETTINGS");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("First Name:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Last Name:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Phone No:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Email:");

        customerFirstNameTF.setEditable(false);
        customerFirstNameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerFirstNameTFActionPerformed(evt);
            }
        });

        customerLastNameTF.setEditable(false);
        customerLastNameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerLastNameTFActionPerformed(evt);
            }
        });

        customerPhoneTF.setEditable(false);
        customerPhoneTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerPhoneTFActionPerformed(evt);
            }
        });

        customerEmailTF.setEditable(false);
        customerEmailTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerEmailTFActionPerformed(evt);
            }
        });

        editBtn.setText("Edit Profile");
        editBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });

        updateBtn.setText("Update Profile");
        updateBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Old Password:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Confirm Password:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("New Password:");

        editPassBtn.setText("Edit Password");
        editPassBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        editPassBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editPassBtnActionPerformed(evt);
            }
        });

        updatePassBtn.setText("Update Password");
        updatePassBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        updatePassBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatePassBtnActionPerformed(evt);
            }
        });

        oldPassPF.setEditable(false);

        newPassPF.setEditable(false);

        confirmNewPassPF.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(customerFirstNameTF, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(customerLastNameTF, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(customerPhoneTF, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(customerEmailTF)
                            .addComponent(oldPassPF, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(newPassPF, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(confirmNewPassPF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(editBtn)
                        .addGap(56, 56, 56)
                        .addComponent(updateBtn)
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(editPassBtn)
                        .addGap(32, 32, 32)
                        .addComponent(updatePassBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(customerFirstNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(customerLastNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(customerPhoneTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(customerEmailTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateBtn)
                    .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(oldPassPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(newPassPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(confirmNewPassPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editPassBtn)
                    .addComponent(updatePassBtn))
                .addGap(20, 20, 20))
        );

        setBounds(260, 20, 500, 468);
    }// </editor-fold>//GEN-END:initComponents

    private void customerFirstNameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerFirstNameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerFirstNameTFActionPerformed

    private void customerLastNameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerLastNameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerLastNameTFActionPerformed

    private void customerPhoneTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerPhoneTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerPhoneTFActionPerformed

    private void customerEmailTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerEmailTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerEmailTFActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        String strFirstName = customerFirstNameTF.getText();
        String strLastName = customerLastNameTF.getText();
        String strEmail = customerEmailTF.getText();
        String strPhone = customerPhoneTF.getText();
        
        try{
            String strDriver = "com.mysql.jdbc.Driver";
            String strConn = "jdbc:mysql://localhost:3306/swcdbms";
            String strUser = "root";
            String strPass = "";
            Class.forName(strDriver);
            Connection objConn = DriverManager.getConnection(strConn,strUser,strPass);
            System.out.println(strCustomerID);
            
            String strQuery = "UPDATE CUSTOMER SET customer_firstname ='"+strFirstName+"', customer_lastname='"+strLastName+"', customer_email='"+strEmail+"', customer_phoneno='"+strPhone+"' WHERE customer_id ="+strCustomerID+"";
            Statement stmntQuery = objConn.prepareStatement(strQuery);
            int intConfirmation = stmntQuery.executeUpdate(strQuery);
            if (intConfirmation == 1){
            infoMessage("Profile Updated.", "SUCCESS!");
            
            }
            else{
                infoMessage("Error updating profile.", "ALERT!");
            }
            
        }catch(Exception objError){
            System.out.println(objError);
        } 
        customerEmailTF.setEditable(false);
        customerFirstNameTF.setEditable(false);
        customerLastNameTF.setEditable(false);
        customerPhoneTF.setEditable(false);
    }//GEN-LAST:event_updateBtnActionPerformed

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        customerEmailTF.setEditable(true);
        customerFirstNameTF.setEditable(true);
        customerLastNameTF.setEditable(true);
        customerPhoneTF.setEditable(true);
    }//GEN-LAST:event_editBtnActionPerformed

    private void editPassBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editPassBtnActionPerformed
        oldPassPF.setEditable(true);
        newPassPF.setEditable(true);
        confirmNewPassPF.setEditable(true);
    }//GEN-LAST:event_editPassBtnActionPerformed

    private void updatePassBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatePassBtnActionPerformed
        String strOldPass = oldPassPF.getText();
        String strNewPass = newPassPF.getText();
        String strConfirmNewPass = confirmNewPassPF.getText();
        try{
            String strDriver = "com.mysql.jdbc.Driver";
            String strConn = "jdbc:mysql://localhost:3306/swcdbms";
            String strUser = "root";
            String strPass = "";
            Class.forName(strDriver);
            Connection objConn = DriverManager.getConnection(strConn,strUser,strPass);
            System.out.println(strCustomerID);
            
            String strQuery = "UPDATE CUSTOMER SET customer_password ='"+strNewPass+"' WHERE customer_id ="+strCustomerID+" AND customer_password ='"+strOldPass+"'";
            Statement stmntQuery = objConn.prepareStatement(strQuery);
            int intConfirmation = stmntQuery.executeUpdate(strQuery);
            if ((intConfirmation == 1)&&(strNewPass.equals(strConfirmNewPass))){
                infoMessage("Password Updated.", "SUCCESS!");
            }
            else{
                infoMessage("Wrong Password. Try again", "ERROR!");
            }
        }catch(Exception objError){
            System.out.println(objError);
        }
        oldPassPF.setText("");
        newPassPF.setText("");
        confirmNewPassPF.setText("");
        oldPassPF.setEditable(false);
        newPassPF.setEditable(false);
        confirmNewPassPF.setEditable(false);
    }//GEN-LAST:event_updatePassBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField confirmNewPassPF;
    private javax.swing.JTextField customerEmailTF;
    private javax.swing.JTextField customerFirstNameTF;
    private javax.swing.JTextField customerLastNameTF;
    private javax.swing.JTextField customerPhoneTF;
    private javax.swing.JButton editBtn;
    private javax.swing.JButton editPassBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPasswordField newPassPF;
    private javax.swing.JPasswordField oldPassPF;
    private javax.swing.JButton updateBtn;
    private javax.swing.JButton updatePassBtn;
    // End of variables declaration//GEN-END:variables
}
